services:
  data_base:
    restart: always
    image: "postgres:15.0"
    container_name: data_base
    volumes:
      - ./data_base/:/var/lib/postgresql/data
    environment:
      PGDATA: "/var/lib/postgresql/pgdata"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5433:5432

  api:
    restart: always
    build: ./api
    env_file:
      - .env
    command: bash -c "uvicorn main:app --reload --workers 4 --host 0.0.0.0 --port 5000"
    ports:
      - 5000:5000
    depends_on:
      - data_base
    volumes:
      - ./api:/api
